name: Package NuGet

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  build-test-package:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup .NET
        uses: actions/setup-dotnet@v4
        with:
          dotnet-version: "8.0.x"

      - name: Run Tests
        run: |
          dotnet test ATM/ATM.Domain.Tests
          dotnet test Payment/Payment.Domain.Tests

      - name: Pack Projects
        run: |
          dotnet pack ATM/ATM.Domain --configuration Release --output ./nupkg
          dotnet pack Payment/Payment.Domain --configuration Release --output ./nupkg

      - name: Push to GitHub Packages
        run: |
          dotnet nuget push ./nupkg/*.nupkg --source "github" --api-key ${{ secrets.GITHUB_TOKEN }}
        env:
          NUGET_AUTH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
